# captured from:
# https://github.com/forcedotcom/sfdx-circleci
# compare to:
# https://github.com/SalesforceCloudServices/demoDxCircleCI
# circle ci 2.0
# https://circleci.com/docs/2.0/
# cron every day at 2am
# https://crontab.guru/every-day-at-2am

version: 2

general:
# Uncomment the following to specify only a specific branch
#    branches:
#      only:
#        - automatedMonitoring
#        - dev # specific branch
#        - /dev-.*/ # or regexes

jobs:
  build:
    runs-on: ubuntu-latest
    working_directory: ~/mern-starter # directory where steps will run
#    docker: # run the steps with Docker
#      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    machine: true
#    working_directory: ~/ci_app
    
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: |
            npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: cleanup old folders
          command: |
            rm -rdf coverage
            rm -rdf tmp
      - run:
          name: Download CLI
          command: |
            mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            ./sfdx/install
            sfdx
            mkdir tmp
      - run:
          name: Run Lint
          command: |
            npm run lint
      - run:
          name: Run Test
          command: |
            npm run test:lwc:coverage
          env:
            CI: true
#      - run:
#          name: Run Apex Tests
#          command: |
#            mkdir -p ~/junit
#            sfdx force:apex:test:run -c -d ~/junit -r junit --wait 5
#      - store_test_results:
#          path: ~/junit

# workflows:
#   version: 2
#   nightly:
#     triggers:
#       - schedule:
#           cron: "0 4 * * *"
#           filters:
#             branches:
#               only:
#                 - automatedMonitoring
#     jobs:
#       - build
