# captured from:
# https://github.com/forcedotcom/sfdx-circleci
# compare to:
# https://github.com/SalesforceCloudServices/demoDxCircleCI
# circle ci 2.0
# https://circleci.com/docs/2.0/
# cron every day at 2am
# https://crontab.guru/every-day-at-2am

version: 2

general:
# Uncomment the following to specify only a specific branch
#    branches:
#      only:
#        - automatedMonitoring
#        - dev # specific branch
#        - /dev-.*/ # or regexes

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    machine: true
    working_directory: ~/ci_app
    
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    
    steps:
      - checkout
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:
          name: cleanup old folders
          command: |
            rm -rdf coverage
            rm -rdf tmp
      - run:
          name: Download CLI
          command: |
            mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            ./sfdx/install
            sfdx
            mkdir tmp
      - run:
          name: npm install
          command: |
            npm install
      - run:
          name: Run Lint
          command: |
            npm run lint
      - run:
          name: Run Test
          command: |
            npm run test:lwc:coverage
          env:
            CI: true
#      - run:
#          name: Run Apex Tests
#          command: |
#            mkdir -p ~/junit
#            sfdx force:apex:test:run -c -d ~/junit -r junit --wait 5
#      - store_test_results:
#          path: ~/junit

# workflows:
#   version: 2
#   nightly:
#     triggers:
#       - schedule:
#           cron: "0 4 * * *"
#           filters:
#             branches:
#               only:
#                 - automatedMonitoring
#     jobs:
#       - build
